name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'
      - name: Install Packages
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Train
        run: python src/train.py
        
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Build and push Docker image
        run: |
          docker build -t <registry-name>.azurecr.io/<image-name>:latest .
          docker login <registry-name>.azurecr.io -u <clientId> -p <clientSecret>
          docker push <registry-name>.azurecr.io/<image-name>:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-web-app-name>
          images: <registry-name>.azurecr.io/<image-name>:latest