# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mlops-grp43

on:
  push:
    branches:
      - azure-deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6abcf587cdb0463daaf6630af1c7f288 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_75532e55e87f43e0898e86498980041b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6abcf587cdb0463daaf6630af1c7f288 }}/news-category-model:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mlops-grp43'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_937776ea85894d28b654fb963b4e42f1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6abcf587cdb0463daaf6630af1c7f288 }}/news-category-model:${{ github.sha }}'