# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mlops-group43

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_576761313e1f4046878ab404eeb18421 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6dfbe4e20484430e965b40e712ab8cf7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_576761313e1f4046878ab404eeb18421 }}/news-category-flask-azure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mlops-group43'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bf243d8b5fbc4b7fa699372a0c98a9b0 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_576761313e1f4046878ab404eeb18421 }}/news-category-flask-azure:${{ github.sha }}'